//CutZYt.mac
//
//
//
//============================================
// (c) Драгункин Александр г.Дубна 2004 г.
//============================================
//
//Создание сечения параллельно ZY  с поворотом


defarr stg1[6] ;

getpar pnt ;
objgab3(pnt,stg1) ;
#sc cut pnt done 3points stg1[1]+(stg1[4]-stg1[1])/2 stg1[2] stg1[3] @0 1000 0 @0 0 1000 ;
rotate sc done 2points stg1[1]+(stg1[4]-stg1[1])/2 stg1[2] stg1[3] stg1[1]+(stg1[4]-stg1[1])/2 stg1[2]+1 stg1[3]  90 nocopy ;
exit ;
