// Установить тек. Типы и Параметры фасадов для библиотеки стандартных объектов
global		// Для фасадов 
DoorMater ,  // Материал панелей (обрамления) фасада
DoorPict,    // тип фасада(рисунка) 
DoorBCol ,   // Цвет кромки фасада
DoorMatVS1 , // Материал вставки 1 фасада
DoorMatVS2 ; // Материал вставки 2 фасада

getpar  P1 P2  P3 P4 P5 ; // 
 
DoorMater=P1;
DoorPict=P2;
DoorBCol=P3;
DoorMatVS1=P4;
DoorMatVS2=P5;

exit