// Установить Отделку профиля для библиотеки стандартных объектов
// В макро разрешено добавлять 1 отделку на профиль
global 
g_PrfDecGr // Группа отделки из групп параметров или 0
g_PrfDecor // Материал отделки из прайса
g_PrfDecVi // Видимость отделки
;

getpar  PrfDecGr PrfDecor PrfDecVi ;
g_PrfDecGr=PrfDecGr // Группа отделки из групп параметров или 0
g_PrfDecor=PrfDecor // Материал отделки из прайса
g_PrfDecVi=PrfDecVi // Видимость отделки

;

exit ;
