x=dbvar("x",300);     //-- Размер по Х
y=dbvar("y",200);     //-- Размер по Y
R=dbvar("R",50);      //-- Радиус R внутреннего скругления
R1=dbvar("R1",50);    //-- Радиус R1 внешнего скругления

pline Normal 0 0 1
      Origin 0 0 0
      ox 1 0 0
      0 0 0
      x 0 0
 arc  direction 0 0 0   //-- Направление дуги
      X-R1 R1 0
 line X-R1 Y-R-R1 0
 arc  X-R-R1 y-R1 0
 line R1 Y-R1 0
 arc  0 Y 0
 line 0 0 0 ;
exit;