//-- Вывод окна сообщения об ошибке
//-- с возвратом кода ошибки в вызывающую программу
//-- Входные параметры:
//-- errname - название ошибки
//-- nErrStr - число строк с описанием ошибки
//-- error[] - массив строк для вывода

getpar errname,nErrStr,error;
if (nErrStr<1)
{
  exit;
}
#ok_flag
alternative "Ошибка!"
msgbox picture 1 beep 1 text left
errname
" "
let i=0
loop:
let i=i+1
error[i]
if (i<nErrStr)
{
  goto loop
}
done
"  OK  "
done;
exit;